services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: softskills_db
      MYSQL_USER: softskills_user
      MYSQL_PASSWORD: softskills_pass
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: softskills-api:latest
    container_name: softskills-app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./logs/api:/app/logs
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/softskills_db
      SPRING_DATASOURCE_USERNAME: softskills_user
      SPRING_DATASOURCE_PASSWORD: softskills_pass
      LOGGING_FILE_NAME: /app/logs/application.log

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: softskills-demo-jwt-frontend:latest
    container_name: softskills-frontend
    depends_on:
      - api
    ports:
      - "8081:80"

volumes:
  mysql_data:
