services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: softskills-api:latest
    container_name: softskills-app
    ports:
      - "8080:8080"
    volumes:
      - ./logs/api:/app/logs
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://sql7.freesqldatabase.com:3306/sql7824795
      SPRING_DATASOURCE_USERNAME: sql7824795
      SPRING_DATASOURCE_PASSWORD: wPSkYUN7R5
      LOGGING_FILE_NAME: /app/logs/application.log

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: softskills-demo-jwt-frontend:latest
    container_name: softskills-frontend
    depends_on:
      - api
    ports:
      - "8081:80"
